### ISSUE TITLE
Studio Test Servers don't work

### ISSUE THREAD

**Issue by Gskartwii** [roblox-linux-wrapper/roblox-linux-wrapper#30] opened 2015-02-03 20:10 UTC
Whenever I start a test server in ROBLOX Studio, the following appears in the output:

```
Failed to start network server, id 5
Script 'http://www.roblox.com/game/gameserver.ashx', Line 199
Script 'loadfile("http://www.roblox.com/game/gameserver.ashx")(0, 5', Line 1
```

stderr doesn't seem to have anything interesting.
I just updated to the newest version. In an older version the output also contained the following error:

```
CURL error (curl_easy_perform, 0033E1F0): SSL connect error
```

**Comment by alfonsojon** [comment] 2015-02-03 20:30
Try running this in the terminal:
```WINEPREFIX=$HOME/.local/share/wineprefixes/roblox-wine-staging WINE=/opt/wine-staging/bin/wine winetricks wininet```

**Comment by Gskartwii** [comment] 2015-02-04 13:48
No, didn't fix it.

**Comment by alfonsojon** [comment] 2015-02-06 02:54
Darn. I'll test this on my PC, and see if anything can be done. Are you sure this isn't an error with Roblox itself? I don't have Windows to test with, so I honestly have no idea.

**Comment by Gskartwii** [comment] 2015-02-07 10:25
I'm 99% positive it worked fine on Win.

**Comment by alfonsojon** [comment] 2015-02-09 02:46
It's working fine on my end, which is odd. I'll be playing with it some more.

**Comment by Gskartwii** [comment] 2015-02-10 15:10
I thought that this might be because I'm on 64-bit wine, maybe? No idea.

**Comment by stormchaser3000** [comment] 2015-02-11 04:04
roblox keeps crashing when i play different games like laser tag or paintball (fixes)

**Comment by alfonsojon** [comment] 2015-02-12 17:12
It should be using the 32-bit prefix by default. While you have 64-bit Wine installed, the 32-bit version is used.

**Comment by Gskartwii** [comment] 2015-02-13 06:12
I thought that maybe winetricks was installing a 64-bit DLL.

**Comment by alfonsojon** [comment] 2015-02-15 03:43
That might have something to do with it. I'll need to test further.

**Comment by alfonsojon** [comment] 2015-03-16 12:48
I can't seem to reproduce this. Is it working properly now?

**Comment by Gskartwii** [comment] 2015-03-16 14:20
I now get the following output:

	16:19:05.004 - Use the new http api: no
	16:19:06.712 - httpGet http://www.roblox.com/game/GetCurrentUser.ashx failed. Trying again. Error: http://www.roblox.com/game/GetCurrentUser.ashx: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:06.712 - httpGet http://clientsettings.api.roblox.com/Setting/QuietGet/ClientAppSettings/?apiKey=D6925E56-BFB9-4908-AAA2-A5B1EC4B2D79 failed. Trying again. Error: http://clientsettings.api.roblox.com/Setting/QuietGet/ClientAppSettings/?apiKey=D6925E56-BFB9-4908-AAA2-A5B1EC4B2D79: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:10.875 - httpGet http://www.roblox.com/game/GetCurrentUser.ashx failed. Trying again. Error: http://www.roblox.com/game/GetCurrentUser.ashx: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:10.876 - http://www.roblox.com/game/GetCurrentUser.ashx: HttpAddRequestHeaders failed, err=0x2F79
	16:19:10.876 - httpGet http://www.roblox.com/game/logout.aspx failed. Trying again. Error: http://www.roblox.com/game/logout.aspx: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0.00198324
	16:19:10.877 - http://www.roblox.com/game/logout.aspx: HttpAddRequestHeaders failed, err=0x2F79
	16:19:10.937 - httpGet http://www.roblox.com/game/gameserver.ashx failed. Trying again. Error: http://www.roblox.com/game/gameserver.ashx: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:10.937 - http://www.roblox.com/game/gameserver.ashx: HttpAddRequestHeaders failed, err=0x2F79
	16:19:10.938 - Script 'loadfile("http://www.roblox.com/game/gameserver.ashx")(0, 5', Line 1
	16:19:10.938 - Stack End
	16:19:10.941 - httpGet http://www.roblox.com/game/gameserver.ashx failed. Trying again. Error: http://www.roblox.com/game/gameserver.ashx: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:10.942 - Content failed for http://www.roblox.com/game/gameserver.ashx because http://www.roblox.com/game/gameserver.ashx: HttpAddRequestHeaders failed, err=0x2F79
	16:19:10.942 - Content failed because http://www.roblox.com/game/gameserver.ashx: HttpAddRequestHeaders failed, err=0x2F79
	16:19:11.011 - httpGet http://www.roblox.com/asset/?id=82741829 failed. Trying again. Error: http://www.roblox.com/asset/?id=82741829: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:11.012 - Content failed for http://www.roblox.com/asset/?id=82741829 because http://www.roblox.com/asset/?id=82741829: HttpAddRequestHeaders failed, err=0x2F79
	16:19:11.012 - Content failed because http://www.roblox.com/asset/?id=82741829: HttpAddRequestHeaders failed, err=0x2F79
	16:19:11.016 - Successfully opened file - C:/users/gskw/AppData/Local/Roblox/server.rbxl
	16:19:12.264 - httpGet http://www.roblox.com/Asset/?id=42557901 failed. Trying again. Error: http://www.roblox.com/Asset/?id=42557901: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:12.264 - httpGet http://www.roblox.com/Asset/?id=104651761 failed. Trying again. Error: http://www.roblox.com/Asset/?id=104651761: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:12.265 - Content failed for http://www.roblox.com/Asset/?id=42557901 because http://www.roblox.com/Asset/?id=42557901: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.265 - Content failed because http://www.roblox.com/Asset/?id=42557901: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.266 - httpGet http://www.roblox.com/Asset/?id=142494219 failed. Trying again. Error: http://www.roblox.com/Asset/?id=142494219: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:12.266 - Content failed for http://www.roblox.com/Asset/?id=104651761 because http://www.roblox.com/Asset/?id=104651761: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.266 - Content failed because http://www.roblox.com/Asset/?id=104651761: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.267 - httpGet http://www.roblox.com/Asset/?id=142494143 failed. Trying again. Error: http://www.roblox.com/Asset/?id=142494143: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:12.267 - httpGet http://www.roblox.com/Asset/?id=143116791 failed. Trying again. Error: http://www.roblox.com/Asset/?id=143116791: HttpAddRequestHeaders failed, err=0x2F79.  Elapsed time: 0
	16:19:12.267 - Content failed for http://www.roblox.com/Asset/?id=142494219 because http://www.roblox.com/Asset/?id=142494219: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.268 - Content failed because http://www.roblox.com/Asset/?id=142494219: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.268 - Content failed for http://www.roblox.com/Asset/?id=142494143 because http://www.roblox.com/Asset/?id=142494143: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.268 - Content failed for http://www.roblox.com/Asset/?id=143116791 because http://www.roblox.com/Asset/?id=143116791: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.269 - Content failed because http://www.roblox.com/Asset/?id=142494143: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.269 - Content failed because http://www.roblox.com/Asset/?id=143116791: HttpAddRequestHeaders failed, err=0x2F79
	16:19:12.858 - Modules is not a valid member of ScreenGui
	16:19:12.859 - Script 'Script Context.StarterScript', Line 60
	16:19:12.859 - Stack End

**Comment by alfonsojon** [comment] 2015-03-16 14:28
Are you using RLW version 20150316?

**Comment by Gskartwii** [comment] 2015-03-16 15:32
Yes.

**Comment by eprent** [comment] 2015-03-16 17:41
[I have this as well, ](http://i.imgur.com/WkLL7Yi.png). It loads halfway and then refuses to connect, if that helps any. Almost sounds like it would be a firewall issue if it was on Windows.

**Comment by alfonsojon** [comment] 2015-03-17 03:16
@Gskartwii I have the script set to use the recommended version of Wine automatically. I suggest using stock Wine for now. I'm looking into this, but it is difficult as it is a Wine bug.

**Comment by Gskartwii** [comment] 2015-03-17 06:22
While I was using stock Wine I was experiencing an error while joining games. I might open an issue for that later.

**Comment by alfonsojon** [comment] 2015-03-17 13:39
Okay, thanks for the report. I need to test further, still...

**Comment by alfonsojon** [comment] 2015-03-17 13:40
I apologize for the slow progress, I do most of my work at school, which also blocks Roblox. As they block access to Roblox, I can't test easily. Sorry!

**Comment by alfonsojon** [comment] 2015-03-20 05:37
@Gskartwii Try running it now (be sure to try the "Reinstall Roblox" option first!)

**Comment by Gskartwii** [comment] 2015-03-21 09:28
No luck. This time the error occurs on line 203.

**Comment by alfonsojon** [comment] 2015-03-27 04:55
@Gskartwii Is this working now?

**Comment by Gskartwii** [comment] 2015-03-27 06:15
Sadly, no. It's all the same as before.

**Comment by alfonsojon** [comment] 2015-03-27 13:41
@Gskartwii That's unfortunate... Can you give me these specs of your system - 
Operating System (32 or 64 bit):
GPU
Proxy info
VPN?

**Comment by Gskartwii** [comment] 2015-03-27 13:55
I'm on Ubuntu 15.04 "Vivid Verlet" 64-bit
My GPU is GeForce GTX 560 Ti.
I'm not using a proxy nor a VPN.

**Comment by alfonsojon** [comment] 2015-03-27 14:13
Have you tried reinstalling since the last update? I don't know if it will
work, but your configuration may be out of date (new RLW, but old wine
prefix). I honestly doubt that this will fix it, but we can hope it will
work. Please keep me updated if this does work!

**Comment by alfonsojon** [comment] 2015-03-27 14:14
@eprent About that issue, it should be taken care of as of 20150320. That was (unfortunately) unrelated to the current issue.

**Comment by Gskartwii** [comment] 2015-03-27 15:04
Yea, still doesn't work...

**Comment by alfonsojon** [comment] 2015-03-27 21:13
@Gskartwii I'm not sure about how the avahi daemon works. Can you try re-enabling it?

**Comment by racquelL** [comment] 2015-03-28 00:47
Hey have you checked on my situation yet and how do i use that number in the terminal what is the command to make the comand line you gave for the roblox wrap? i am a total dummy in this...

**Comment by Gskartwii** [comment] 2015-03-28 08:01
Apparently Avahi is used for finding what computers are connected to the local network and my has done something so that it doesn't work (Don't know why)

**Comment by racquelL** [comment] 2015-03-28 12:36
it does not give me the allow and allow and remember button anymore...it seemed like it is working but then i got this message...Program Error   the program Roblox PlayerBeta.exe has encountered a serious problem and needs to close. We are sorry for rhe inconvenience. This can be caused by a problem or a deficiancy in Wine. You may want to check the Application Database for tips about runing this application

then I got Roblox Linux Wrapper v20150326 wine closed unsuccessfully. see terminal for details. (exit code1) waiting anxiously for your response

**Comment by alfonsojon** [comment] 2015-03-28 17:39
@racquelL Please open a separate issue to report that, rather than commenting on any open issue reports.

**Comment by alfonsojon** [comment] 2015-03-28 17:40
@Gskartwii So, from what I've gathered, CURL cannot use SSL (HTTPS) on your system for some odd reason. Even if it did, the game wouldn't work, as it requires SSL (HTTPS). Do websites that use SSL, such as Gmail work properly?

**Comment by Gskartwii** [comment] 2015-03-28 20:31
They do; they are probaly using a different library.
I checked what line 203 was in gameserver.ashx. It's the one starting the network server. Since other kinds of network servers like nginx work on my system, I'm guessing that it's a Wine bug.

**Comment by alfonsojon** [comment] 2015-04-16 15:23
@Gskartwii Can you test this in a virtual machine with an out-of-box OS installed, with only the dependencies installed? If it works in the VM, then the issue is most likely system-specific and cannot be fixed by the wrapper. If it does not work in the VM either, I'll try to find the root cause of the issue.

**Comment by GLolol** [comment] 2015-04-16 16:48
It seems like Avahi is having a conflict with what's possibly your ISP's DNS settings:

http://avahi.org/wiki/AvahiAndUnicastDotLocal
https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/327362

**Comment by Gskartwii** [comment] 2015-04-16 18:09
@alfonsojon Thanks for your effort. I happened to find an old VM with Precise. I'll let it take its time to upgrade (to get a newer version of Wine) and will post again.
@GLolol I don't think that Avahi is the problem here since it's only used for finding computers connected to the local network.

**Comment by GLolol** [comment] 2015-04-16 18:49
> EDIT: Just thought, I wonder if the Avahi daemon being disabled affects it. (Every time I connect to the Internet I see a warning about my network having a .local domain)
If your ISP is also mapping addresses to `.local`, there will be a conflict.

**Comment by Gskartwii** [comment] 2015-05-06 16:07
Uh totally forgot about this...
And yea, it still won't work on the VM.

**Comment by baphvince** [comment] 2015-05-21 16:21
Still having this issue on an Arch Linux system.

**Comment by alfonsojon** [comment] 2015-05-21 17:18
Based on input, it seems a port may need to be opened through iptables, although this is pure speculation and I do not know which port needs to be opened.

**Comment by Gskartwii** [comment] 2015-06-04 10:57
On Windows it starts the server on port 53640, possibly that?

**Comment by GLolol** [comment] 2015-06-04 14:21
Most likely, yes. Most firewalls should allow localhost traffic unfiltered however, so it could be a bug causing the test servers to break OR a firewall misconfiguration - I can't tell.

**Comment by alfonsojon** [comment] 2015-07-20 13:46
@Gskartwii Is this working now? Unfortunately, the issue is not caused by our code, so I do not see how we can resolve the issue.

**Comment by Gskartwii** [comment] 2015-07-26 09:04
Just tried on a VM, no luck. I will try the iptables thing ASAP.

**Comment by Gskartwii** [comment] 2015-08-05 17:35
I tried to open the ports with iptables. `iptables -L` now looks like this:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:53640

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:53640

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:53640
```

**Comment by ZarsBranchkin** [comment] 2017-07-30 20:05
Managed to find where this issue originates from. It's an wine winsock bug/incompatibility with roblox studio. Roblox studio attempts to bind it's port on all available interfaces, but due some magic wine interface translation, it ends up trying to bind same port.

The exact problematic line is this one: 
https://github.com/wine-mirror/wine/blob/989a9dc91778c94d0cf0c769709f10dcc92a5ead/dlls/ws2_32/socket.c#L3331

Getting rid of it fixes the roblox studio test server.

**Comment by alfonsojon** [comment] 2020-06-12 21:06
Closed as it no longer impacts latest versions of wine based on testing

**Closed** 2020-06-12 21:05 UTC
Labels: bug, closing-if-no-info, system-specific

**Comment by matej118111** [comment] 2022-06-28 11:29
Wow, issue from 2015, very cool
