### ISSUE TITLE
ROBLOX works for a few seconds AND then it says "this game has shut down"

### ISSUE THREAD

**Issue by Chickenmax** [roblox-linux-wrapper/roblox-linux-wrapper#142] opened 2015-07-29 00:27 UTC
LOL it doesnt works months ago with older wine versions it runned for a few seconds and it said " an unexpeced error has ocurred and roblox needs to quit"  but now it says that IT doesnt work on wine or wine stagging PLIZ HELP

**Comment by GLolol** [comment] 2015-07-29 00:35
Duplicate of #135... But apparently you were aware of that :|

**Closed by GLolol** 2015-07-29 00:35 UTC
