### ISSUE TITLE
wineserver --wait not working with wine-staging, implement workaround

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#110] opened 2015-05-19 17:34 UTC
For some reason, wineserver --wait is not working with wine-staging. A workaround should be applied in order to fix this.

**Comment by GLolol** [comment] 2015-06-08 14:12
Can this be reproduced with Wine staging 1.7.44?

**Comment by GLolol** [comment] 2015-06-12 05:03
Marking as fixed since I can no longer reproduce on staging 1.7.44.

**Closed by GLolol** 2015-06-12 05:03 UTC
Labels: bug, fixed-upstream, needs-info
