### ISSUE TITLE
RoL has been fixed

### ISSUE THREAD

**Issue by Reinitialized** [roblox-linux-wrapper/roblox-linux-wrapper#191] opened 2021-06-11 22:31 UTC
Was going to bump the old issue, but seems it been locked.

After much time, RoL has been fixed. [You can see the specific details here on the changes.](https://source.winehq.org/patches/data/207636) Credit goes to Slappy826 for figuring out the problem. This should be getting merged into mainstream WINE in the coming weeks.

**Comment by alfonsojon** [comment] 2021-06-11 22:46
Thank you for that update! I will keep an eye upstream for when this patch hits the staging branch so I can test.

**Comment by Percslol** [comment] 2021-06-12 00:00
ROBLOX FOR LINUX IS BACK LETS GOOOOOOOOOOOOOOOOOOO

**Comment by Nolij** [comment] 2021-06-12 01:13
Got wine to build with his patch. Can confirm Roblox is once again playable on Wine!

Note: for me at least mouse movement was slightly buggy but I was on wine, not wine-staging, not proton. I'll be building proton soon and posting an update here after I get it built with the patch to see how the game plays. For now though this is MUCH better than before. HUGE props to Slappy826 for this patch.

**Comment by lucasburlingham** [comment] 2021-06-12 02:29
This is probably the most important thing to happen to Linux gaming this year. Thank you!

**Comment by Nolij** [comment] 2021-06-12 02:51
Update: built Proton with the patch. As expected things are smoother now but the mouse issue still remains. It happens when I try to move my camera. I'm trying to figure out if this is a wine issue or a KDE Plasma issue (the display environment I use). I can share my Proton build with those who wish to use it before the patch is merged in to mainline Steam who don't want to build it themselves. I would very much appreciate testing of this issue. To reproduce the issue open Roblox, and right click to move your camera. After that you will be unable to move your mouse until you ALT+TAB out if you're having the same issue I am.

**Comment by alfonsojon** [comment] 2021-06-12 08:24
I have unlocked the main issue #135

**Closed by alfonsojon** 2021-06-12 08:24 UTC

**Comment by theopensour** [comment] 2021-06-12 16:02
instructions to build?

**Comment by theopensour** [comment] 2021-06-12 16:03
> Update: built Proton with the patch. As expected things are smoother now but the mouse issue still remains. It happens when I try to move my camera. I'm trying to figure out if this is a wine issue or a KDE Plasma issue (the display environment I use). I can share my Proton build with those who wish to use it before the patch is merged in to mainline Steam who don't want to build it themselves. I would very much appreciate testing of this issue. To reproduce the issue open Roblox, and right click to move your camera. After that you will be unable to move your mouse until you ALT+TAB out if you're having the same issue I am.

when?

**Comment by Nolij** [comment] 2021-06-12 17:13
> > Update: built Proton with the patch. As expected things are smoother now but the mouse issue still remains. It happens when I try to move my camera. I'm trying to figure out if this is a wine issue or a KDE Plasma issue (the display environment I use). I can share my Proton build with those who wish to use it before the patch is merged in to mainline Steam who don't want to build it themselves. I would very much appreciate testing of this issue. To reproduce the issue open Roblox, and right click to move your camera. After that you will be unable to move your mouse until you ALT+TAB out if you're having the same issue I am.
> 
> when?

The issue is confirmed to be global. Not much we can do about it at the moment.

Someone posted a patch in the Grapejuice Discord server, but its a bit janky and doesn't work 100% of the time (also doesn't fix other things that grab your mouse such as first person and shift lock switch). Won't be merged upstream.

The fact that the patch exists though gives me hope that there will be an actual patch that isn't a band-aid fix and we will have basically flawless experience on Linux.

**Comment by theopensour** [comment] 2021-06-12 21:43
> Update: built Proton with the patch. As expected things are smoother now but the mouse issue still remains. It happens when I try to move my camera. I'm trying to figure out if this is a wine issue or a KDE Plasma issue (the display environment I use). I can share my Proton build with those who wish to use it before the patch is merged in to mainline Steam who don't want to build it themselves. I would very much appreciate testing of this issue. To reproduce the issue open Roblox, and right click to move your camera. After that you will be unable to move your mouse until you ALT+TAB out if you're having the same issue I am.

When
