### ISSUE TITLE
ROBLOX & Firefox don't work together.

### ISSUE THREAD

**Issue by merrrickal900** [roblox-linux-wrapper/roblox-linux-wrapper#122] opened 2015-06-08 02:22 UTC
Hi. I'm experimenting using ROBLOX Linux Wrapper on a Chromebook. I've seen other solutions, but I'm not sure if they're genuine, native and/or permanent. I'm using Trusty Tahr LTS installed via Crouton. The Chromebook is an Intel powered Chromebook. The Asus C300MADH02 to be exact. I don't know if this is the right place to place this issue, but I've just installed ROBLOX Linux Wrapper today and I cannot run ROBLOX and Firefox correctly (either one or the other). Using Wine, I can successfully play a ROBLOX game (Framed 2.2), but Firefox always closes fast and may not even stay open long enough for me to open a game. Using Wine-staging, I can run Firefox without it closing (or not as long as with Wine, yet to be confirmed). But I cannot run any ROBLOX game. I saw that Internet Explorer is in the ROBLOX drive, but I'm not sure how to run it alongside ROBLOX. And I can't find a solution under any other similar issues (or may not understand them). Is there any way to possibly fix this issue and/or use Internet Explorer instead? If neither, is there a solution in the works? Thanks for any help in advance if any at all.

**Comment by GLolol** [comment] 2015-06-08 02:42
If Firefox is crashing under Wine, then that's a bug. The version of IE bundled in Wine is a heavily patched version if IE6 as far as I know; it shouldn't be relied upon and it is definitely not supported by us.

Roblox Linux Wrapper uses Firefox on Windows because Roblox uses a browser plugin to start games. Currently, only Firefox works well enough under Wine for this to work, but there have been issues too.

Per https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/CONTRIBUTING.md#information-needed-in-a-bug-report,

* What Wine version are you running?

**Comment by alfonsojon** [comment] 2015-06-08 02:52
@merrrickal900 @GLolol The built in "Internet Explorer" uses the Gecko rendering engine, with some custom, ugly UI slapped onto it. I know JavaScript support is broken, if even existent in it. Firefox is the only browser that I know of that works well under Wine, and with all the changes they're making, even Firefox is becoming less and less stable on Wine. I am working on a custom Roblox browser, but I do not know when I will have a functional build ready for distribution.

**Comment by merrrickal900** [comment] 2015-06-08 02:55
@GLolol @alfonsojon I believe I'm using Wine 1.7.44 because it came out recently and I just installed Wine 1.7 today (but I've used Wine before on a different system besides my Chromebook), but I'm honestly not 100% sure about it. As for Wine-staging, I have no idea of what version I could possibly be on, but if it helps I just installed that for the first time today via the command for the recommended version of Wine-staging. Thank you for the update on the custom ROBLOX browser.

**Comment by alfonsojon** [comment] 2015-06-08 03:00
@merrrickal900 Open a terminal, run `wine --version`. Also, Chromebook setups are not supported unless booting a full installation of Linux. Crouton and Chrubuntu are not supported.

**Comment by merrrickal900** [comment] 2015-06-08 03:53
I'm terribly sorry for the late reply. The Wine version I have is  1.7.38. If the problem is graphics related, the game runs perfectly whenever it does decide to run if that helps anything.

**Comment by alfonsojon** [comment] 2015-06-08 04:15
@merrrickal900 Try running wine-staging; [a quick Google search](https://www.google.com/search?q=wine-staging) will yield great results :+1:

**Comment by merrrickal900** [comment] 2015-06-08 04:35
I've gotten the same results. Running ROBLOX with Wine allows the game to run, but the browser can barely stay open at all. Running ROBLOX with Wine-staging allows the browser to run correctly, but the game refuses to open.

**Comment by GLolol** [comment] 2015-06-08 04:56
As far as I know, the Firefox crashing issue is fixed in Wine 1.7.44 (issue #116), but that hasn't arrived in the Ubuntu PPA yet. You'll have to wait until that becomes available.

**Comment by merrrickal900** [comment] 2015-06-08 05:12
Oh. Ok. I thought that Wine 1.7.44 was already released. Thank you for the heads-up.

**Comment by GLolol** [comment] 2015-06-08 13:54
It is released (hence the version), but not available in the Ubuntu PPA yet.

**Comment by GLolol** [comment] 2015-06-12 05:33
Closing as fixed upstream (wait for it to be released in the PPA) and a duplicate of #116.

**Closed by GLolol** 2015-06-12 05:33 UTC
Labels: needs-info, wine-bug
