### ISSUE TITLE
Unable to launch game Roblox

### ISSUE THREAD

**Issue by coreybruce** [roblox-linux-wrapper/roblox-linux-wrapper#173] opened 2017-07-15 04:43 UTC
Website asks for me to install roblox  even tho it is installed.

**Comment by GLolol** [comment] 2017-08-05 17:25
Duplicate of #172

**Closed by GLolol** 2017-08-05 17:25 UTC
Labels: bug, duplicate

**Comment by CharlesNadolski** [comment] 2018-01-05 04:27
Same issue.  Installed roblox using the linux wrapper, can't launch a game from Firefox (prompts to download an install roblox).
rlw --version
Sourcing /usr/share/roblox-linux-wrapper/data/rlw-core.sh
wine path set to /usr/bin/wine
wineboot path set to /usr/bin/wineboot
wineserver path set to /usr/bin/wineserver
Roblox Linux Wrapper 2017.06.21
firefox --version
Mozilla Firefox 57.0.3
