### ISSUE TITLE
WHEN I PRESS R MOUSE CLICK I CANT MOVE MOUSE INSIDE GAME

### ISSUE THREAD

**Issue by nttainBaka** [roblox-linux-wrapper/roblox-linux-wrapper#196] opened 2021-06-23 04:31 UTC
when i press right click button on my mouse i cant move my cursor after so the only i can play is funkin friday!!

**Comment by nttainBaka** [comment] 2021-06-23 04:38
_**pls fix this quick or i will cant play roblox **_

**Comment by nttainBaka** [comment] 2021-06-23 04:39
i was trying to play [this game](https://web.roblox.com/games/20321167/Pilot-Training-Flight-Simulator#) but i cant! i need to move mouse with r button

**Comment by Vencorr** [comment] 2021-06-23 22:18
Think this is a duplicate of #195.

**Comment by nttainBaka** [comment] 2021-06-24 19:52
I VE FOUND WAY TO UNLOCKED MOUSE!! i am in fedora 34 so idk if will work in mint ubuntu or any other distro, the way i ve found is press alt + tab 2 times

**Comment by alfonsojon** [comment] 2021-06-24 19:53
Closed as duplicate of #195

**Closed by alfonsojon** 2021-06-24 19:53 UTC

**Comment by nttainBaka** [comment] 2021-06-28 23:44
what is duplicate?

**Comment by nttainBaka** [comment] 2021-06-28 23:44
ik what is 
but i mean why you close being duplicate?

**Comment by Vencorr** [comment] 2021-06-28 23:56
Because it is a duplicate, and there is already a current issue opened about this issue.
